name: Sync Docker Images to Cache Registry

on:
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - "src.yaml"
  schedule:
    - cron: "22 18 * * *" # 每晚 02:22 运行
jobs:
  sync-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      - name: Login to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          skopeo login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
      - name: Sync Images
        run: |
          skopeo sync --src yaml --dest docker src.yaml $DOCKER_REGISTRY
